In [1]:
import pickle
import pandas as pd
import numpy as np

with open('slice_data.pickle', 'rb') as handle:
    raw_data = pickle.load(handle)


data = raw_data['ACC_FS']


n_column = data.iloc[0,:].size


starting_index = np.arange (1,n_column+1, 15)

cell_list = []

#separate the cells from one sheet

for i in starting_index:
    cell_data = data.iloc[:,i:i+13]
    cell_list.append(cell_data)


clamp_levels = data.iloc[0,1:14]

clamp_levels_string = pd.Series(clamp_levels, dtype="string")

col_list = list(clamp_levels_string)

In [2]:
raw_data.keys()

dict_keys(['ACC_FS', 'PPC_FS', 'ACC_RS', 'PPC_RS'])

In [10]:
def into_dict(data):
    n_column = data.iloc[0,:].size
    starting_index = np.arange (1,n_column+1, 15)

    cell_list = []
    clamp_levels = data.iloc[0,1:14]
    clamp_levels_string = pd.Series(clamp_levels, dtype="string")
    col_label = list(clamp_levels_string)


    #separate the cells from one sheet

    for i in starting_index:
        cell_data = data.iloc[:,i:i+13]
        cell_list.append(cell_data)

    num_neuron = len(cell_list)
    cell_id_list = []


    for i in range(num_neuron):
        col_list = list(cell_list[i].columns)
        cell_id = col_list[0]
        cell_id_list.append(cell_id)


    num_neuron = len(cell_list)
    cell_id_list = []
    for i in range(num_neuron):
        col_list = list(cell_list[i].columns)
        cell_id = col_list[0]
        cell_id_list.append(cell_id)
        sheet_time = data.iloc[1:,0]


    for i in range(num_neuron):
        cell_list[i].columns = col_label
        cell_list[i] = cell_list[i].iloc[1:,:]


    cell_dic = {}

    cell_dic['time'] = sheet_time
    cell_dic['data'] = cell_list
    cell_dic['cell_id'] =  cell_id_list

    return cell_dic

In [11]:
acc_rs = into_dict(raw_data['ACC_RS'])

In [12]:
a = acc_rs['data']

In [13]:
(acc_rs['data'][1])

,-200.0,-150.0,-100.0,-50.0,0.0,50.0,100.0,150.0,200.0,250.0,300.0,350.0,400.0
1,-70.1294,-67.9321,-67.9626,-68.2983,-68.5730,-69.5496,-70.5566,-71.7163,-72.0825,-72.8455,-73.6694,-74.0356,-74.4934
2,-70.1294,-67.9321,-67.9626,-68.2983,-68.5730,-69.5496,-70.5261,-71.7163,-72.1130,-72.8149,-73.6694,-74.0356,-74.4934
3,-70.1294,-67.9321,-67.9626,-68.2983,-68.5730,-69.5801,-70.5566,-71.7163,-72.1130,-72.8455,-73.6389,-74.0356,-74.4934
4,-70.1294,-67.9321,-67.9321,-68.3289,-68.5730,-69.5801,-70.5566,-71.7163,-72.0825,-72.8149,-73.6694,-74.0356,-74.4934
5,-70.1294,-67.9626,-67.9321,-68.3289,-68.6035,-69.5496,-70.5566,-71.7163,-72.0825,-72.8455,-73.6694,-74.0051,-74.4934
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
n_cell_types = len(raw_data)

In [15]:
raw_data.keys()

dict_keys(['ACC_FS', 'PPC_FS', 'ACC_RS', 'PPC_RS'])

In [16]:
cell_types = list(raw_data.keys())

In [17]:
cell_types[0]

'ACC_FS'

In [18]:
org_data = {}

In [19]:
abs

In [20]:
for i in range(4):
    org_data[cell_types[i]] =  into_dict(raw_data[cell_types[i]])

In [21]:
org_data.keys()

dict_keys(['ACC_FS', 'PPC_FS', 'ACC_RS', 'PPC_RS'])

In [22]:
org_data['ACC_FS'].keys()

dict_keys(['time', 'data', 'cell_id'])

In [27]:
len(org_data['ACC_RS']['data'])

16

In [28]:
org_data['ACC_RS']['data']

[         -200.0    -150.0    -100.0     -50.0      0.0     50.0   100.0  \
 1      0.223013  0.639664  0.190828  0.265515 -71.5027 -72.5403 -73.822
 2     -0.021128  0.426041  0.373933  0.265515 -71.2891 -72.6013 -73.700
 3      0.223013  0.395524  0.465486  0.234998 -71.4417 -72.4792 -73.822
 4      0.223013  0.487077  0.373933 -0.039661 -71.5637 -72.3572 -73.822
 5      0.345083  0.456559  0.557038  0.143445 -71.5942 -72.4792 -73.822
 ...         ...       ...       ...       ...      ...      ...     ...
 11996       NaN       NaN       NaN       NaN      NaN      NaN     NaN
 11997       NaN       NaN       NaN       NaN      NaN      NaN     NaN
 11998       NaN       NaN       NaN       NaN      NaN      NaN     NaN
 11999       NaN       NaN       NaN       NaN      NaN      NaN     NaN
 12000       NaN       NaN       NaN       NaN      NaN      NaN     NaN

          150.0    200.0    250.0    300.0    350.0    400.0
 1     -74.7070 -76.2939 -77.5146 -78.8269 -79.1931 -79.3152
 2     -74.4934 -76.1719 -77.3926 -78.9490 -79.1321 -79.4067
 3     -74.4629 -76.2634 -77.2400 -78.7048 -79.3762 -79.2542
 4     -74.5544 -76.5076 -77.4536 -78.6133 -79.3762 -79.1626
 5     -74.2493 -76.3855 -77.5146 -78.7048 -79.1931 -79.3762
 ...        ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -70.1294 -67.9321 -67.9626 -68.2983 -68.5730 -69.5496 -70.5566 -71.7163
 2     -70.1294 -67.9321 -67.9626 -68.2983 -68.5730 -69.5496 -70.5261 -71.7163
 3     -70.1294 -67.9321 -67.9626 -68.2983 -68.5730 -69.5801 -70.5566 -71.7163
 4     -70.1294 -67.9321 -67.9321 -68.3289 -68.5730 -69.5801 -70.5566 -71.7163
 5     -70.1294 -67.9626 -67.9321 -68.3289 -68.6035 -69.5496 -70.5566 -71.7163
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -72.0825 -72.8455 -73.6694 -74.0356 -74.4934
 2     -72.1130 -72.8149 -73.6694 -74.0356 -74.4934
 3     -72.1130 -72.8455 -73.6389 -74.0356 -74.4934
 4     -72.0825 -72.8149 -73.6694 -74.0356 -74.4934
 5     -72.0825 -72.8455 -73.6694 -74.0051 -74.4934
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0  150.0  \
 1     -77.9419 -76.6296 -77.3926 -77.2095 -77.3315 -76.8433 -76.8738 -77.24
 2     -77.9419 -76.6296 -77.3621 -77.2095 -77.3315 -76.8433 -76.8738 -77.24
 3     -77.9419 -76.6602 -77.3621 -77.2400 -77.3315 -76.8433 -76.8738 -77.24
 4     -77.9724 -76.6296 -77.3926 -77.2400 -77.3010 -76.8433 -76.8433 -77.24
 5     -77.9419 -76.6296 -77.3621 -77.2400 -77.3315 -76.8433 -76.8738 -77.24
 ...        ...      ...      ...      ...      ...      ...      ...    ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN    NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN    NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN    NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN    NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN    NaN

          200.0    250.0    300.0    350.0    400.0
 1     -77.9724 -79.8645 -81.0242 -81.0852 -81.6956
 2     -77.9419 -79.8950 -81.0547 -81.0852 -81.6956
 3     -77.9419 -79.8645 -81.0547 -81.1157 -81.6650
 4     -77.9419 -79.8950 -81.0242 -81.1157 -81.6650
 5     -77.9419 -79.8645 -81.0547 -81.0852 -81.6956
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -71.8079 -67.7795 -68.5120 -68.8782 -69.9158 -70.6787 -73.9441 -75.8972
 2     -71.7468 -67.8406 -68.2678 -69.0002 -69.8242 -70.5261 -73.8220 -75.8362
 3     -71.8689 -67.8711 -68.4204 -68.7866 -69.9158 -70.8923 -73.9441 -75.7446
 4     -71.7163 -67.8406 -68.2068 -68.7866 -69.7327 -70.7092 -73.9136 -75.8667
 5     -71.7468 -68.0847 -68.3899 -68.6951 -69.8242 -70.9839 -73.7915 -75.6531
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -76.9043 -77.7283 -78.1250 -78.0334 -78.3386
 2     -77.2400 -77.5757 -78.1555 -77.8809 -78.5522
 3     -76.9348 -77.7283 -77.9114 -78.0945 -78.6133
 4     -77.0264 -77.4231 -78.2166 -77.8809 -78.5217
 5     -76.9653 -77.6367 -78.0640 -77.9724 -78.4607
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -71.0144 -70.9229 -70.8618 -70.4346 -70.8923 -70.8313 -70.7397 -70.6787
 2     -71.0449 -70.9229 -70.9229 -70.4346 -71.0144 -70.8313 -70.8313 -70.7397
 3     -70.9839 -70.8008 -70.9839 -70.4346 -71.0449 -70.7397 -70.7092 -70.7092
 4     -71.0449 -70.6482 -70.9534 -70.5566 -70.9534 -70.9534 -70.9534 -70.8008
 5     -71.1975 -70.8313 -70.8008 -70.6482 -70.9534 -70.8008 -70.8923 -70.7092
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -71.8689 -72.2961 -72.9675 -73.0286 -72.9675
 2     -72.0215 -72.2351 -72.8149 -72.9675 -73.0286
 3     -71.8689 -72.2351 -72.9370 -72.9675 -72.9065
 4     -71.9604 -72.2351 -72.8455 -72.9065 -72.9675
 5     -71.8689 -72.2046 -72.9370 -72.9675 -72.9675
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -61.1572 -61.7065 -61.8286 -63.5071 -66.4368 -67.2607 -65.9485 -64.4531
 2     -61.1267 -61.8286 -61.6760 -63.3850 -66.2231 -67.0776 -66.1316 -64.5447
 3     -61.1877 -61.7676 -61.8286 -63.4766 -66.4062 -67.3218 -65.9485 -64.4836
 4     -61.0962 -61.7371 -61.7371 -63.3545 -66.2537 -67.0776 -66.0706 -64.6057
 5     -61.2488 -61.9202 -61.7065 -63.3545 -66.3147 -67.3218 -66.0400 -64.4531
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -63.8733 -63.8123 -64.2700 -61.7371 -61.2488
 2     -64.0259 -63.9648 -64.0259 -61.7371 -61.4319
 3     -63.9343 -63.9038 -64.0869 -61.6455 -61.2488
 4     -64.0564 -63.9648 -64.0259 -61.7371 -61.4014
 5     -63.9343 -63.9038 -63.9648 -61.6760 -61.3403
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -74.2493 -72.6929 -73.3337 -71.8689 -73.7610 -74.0051 -75.2869 -76.9348
 2     -74.2188 -72.6318 -73.1201 -71.9604 -73.8525 -73.9136 -75.2869 -77.0264
 3     -74.2798 -72.8149 -73.1812 -71.9299 -73.7915 -73.8220 -75.1953 -76.8738
 4     -74.1882 -72.7234 -73.2727 -71.7468 -73.7915 -73.8525 -75.2258 -76.8738
 5     -74.3408 -72.6013 -73.3032 -71.9299 -73.8220 -73.7915 -75.1648 -76.8127
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -79.2236 -79.6814 -80.0781 -79.8340 -80.0781
 2     -79.1626 -79.7729 -79.9866 -79.7729 -80.0171
 3     -79.2236 -79.6509 -80.3223 -79.8950 -79.9255
 4     -79.1016 -79.8950 -80.0781 -79.8035 -80.0171
 5     -79.1626 -79.7729 -80.1086 -79.8645 -79.8340
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -68.3899 -64.4226 -65.3687 -65.1550 -66.6199 -67.9932 -68.4204 -68.8782
 2     -68.3899 -64.4226 -65.3687 -65.1245 -66.6199 -67.9932 -68.4204 -68.8782
 3     -68.3899 -64.4531 -65.3381 -65.1245 -66.6199 -67.9932 -68.4204 -68.8782
 4     -68.3899 -64.4226 -65.3687 -65.1245 -66.5894 -67.9932 -68.3899 -68.9087
 5     -68.3899 -64.4531 -65.3992 -65.1245 -66.5894 -67.9932 -68.3899 -68.9087
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -69.0002 -69.8547 -69.9158 -70.3125 -70.3430
 2     -69.0002 -69.8547 -69.9158 -70.3125 -70.3430
 3     -69.0002 -69.8547 -69.9158 -70.3430 -70.3430
 4     -69.0002 -69.8547 -69.9158 -70.3125 -70.3125
 5     -69.0002 -69.8242 -69.8853 -70.3125 -70.3125
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -84.1980 -83.9844 -84.0454 -83.9233 -83.9233 -83.9233 -83.9539 -84.0759
 2     -84.1980 -83.9844 -84.0454 -83.9233 -83.9539 -83.9233 -83.9539 -84.0759
 3     -84.1675 -83.9844 -84.0149 -83.8928 -83.9539 -83.9233 -83.9539 -84.0759
 4     -84.1675 -83.9844 -84.0149 -83.9233 -83.9539 -83.8928 -83.9539 -84.0759
 5     -84.1675 -83.9539 -84.0149 -83.9233 -83.9233 -83.9233 -83.9539 -84.0454
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -83.9844 -84.1370 -84.1675 -84.2590 -84.1675
 2     -83.9539 -84.1064 -84.1370 -84.2590 -84.1370
 3     -83.9844 -84.1064 -84.1675 -84.2285 -84.1675
 4     -83.9539 -84.1064 -84.1675 -84.2590 -84.1675
 5     -83.9539 -84.1064 -84.1980 -84.2590 -84.1370
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -74.1577 -73.9136 -73.6084 -74.0356 -73.5168 -73.7610 -73.8831 -76.0803
 2     -74.1882 -73.9136 -73.5168 -73.9136 -73.6084 -73.7305 -73.8831 -76.2634
 3     -74.0967 -73.8525 -73.5168 -74.0356 -73.5168 -73.7610 -73.9441 -76.0803
 4     -74.2188 -73.9136 -73.5474 -73.8220 -73.7915 -73.8525 -73.8525 -76.1414
 5     -74.1577 -73.8220 -73.6084 -74.0051 -73.4863 -73.7915 -73.9136 -76.1108
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -77.5757 -78.8574 -79.2236 -79.9561 -80.0781
 2     -77.5146 -78.9795 -79.3152 -79.9866 -80.1086
 3     -77.6367 -78.8269 -79.2236 -79.9866 -80.0781
 4     -77.5452 -78.9490 -79.3457 -79.9561 -80.0781
 5     -77.6672 -78.8269 -79.1931 -79.9561 -80.1392
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
          -200.0   -150.0    -100.0     -50.0      0.0    50.0    100.0  \
 1      0.033127  0.32025  0.158513  0.203184 -70.9229 -71.106 -73.2117
 2      0.033127  0.32025  0.189031  0.203184 -70.9229 -71.106 -73.2422
 3      0.033127  0.32025  0.189031  0.203184 -70.9229 -71.106 -73.2117
 4      0.033127  0.32025  0.189031  0.203184 -70.9229 -71.106 -73.2117
 5      0.033127  0.32025  0.189031  0.172667 -70.9229 -71.106 -73.2117
 ...         ...      ...       ...       ...      ...     ...      ...
 11996       NaN      NaN       NaN       NaN      NaN     NaN      NaN
 11997       NaN      NaN       NaN       NaN      NaN     NaN      NaN
 11998       NaN      NaN       NaN       NaN      NaN     NaN      NaN
 11999       NaN      NaN       NaN       NaN      NaN     NaN      NaN
 12000       NaN      NaN       NaN       NaN      NaN     NaN      NaN

          150.0    200.0    250.0    300.0    350.0    400.0
 1     -75.0122 -76.2329 -77.3315 -78.5828 -78.9490 -78.9795
 2     -75.0122 -76.2329 -77.3315 -78.5828 -78.9490 -78.9795
 3     -75.0122 -76.2329 -77.3315 -78.5828 -78.9490 -78.9795
 4     -74.9817 -76.2329 -77.3315 -78.5828 -78.9185 -78.9795
 5     -74.9817 -76.2329 -77.3010 -78.5828 -78.9490 -79.0100
 ...        ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -81.3293 -82.0007 -81.6345 -81.4514 -82.2144 -81.8787 -82.3364 -83.0078
 2     -81.3293 -82.0007 -81.6345 -81.4514 -82.2144 -81.8787 -82.3669 -82.9773
 3     -81.3293 -82.0007 -81.6345 -81.4514 -82.2144 -81.8787 -82.3364 -82.9773
 4     -81.3293 -82.0007 -81.6345 -81.4514 -82.2144 -81.8787 -82.3669 -82.9468
 5     -81.3599 -82.0007 -81.6345 -81.4514 -82.2144 -81.8787 -82.3364 -82.9468
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

          200.0    250.0    300.0    350.0    400.0
 1     -83.7708 -83.8318 -84.7778 -85.2356 -85.9985
 2     -83.7708 -83.8318 -84.7778 -85.2051 -85.9985
 3     -83.7708 -83.8623 -84.7778 -85.2051 -85.9985
 4     -83.7708 -83.8623 -84.7778 -85.2356 -85.9985
 5     -83.7708 -83.8623 -84.7778 -85.2051 -85.9985
 ...        ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN
 11997      NaN      NaN      NaN      NaN      NaN
 11998      NaN      NaN      NaN      NaN      NaN
 11999      NaN      NaN      NaN      NaN      NaN
 12000      NaN      NaN      NaN      NaN      NaN

 [12000 rows x 13 columns],
         -200.0   -150.0   -100.0    -50.0      0.0     50.0    100.0    150.0  \
 1     -82.3669 -81.1768 -81.5430 -81.8176 -81.4209 -83.2520 -82.4280 -82.4890
 2     -82.4585 -81.2683 -81.6956 -81.6956 -81.2073 -83.3435 -82.4890 -82.4585
 3     -82.3975 -81.2378 -81.6040 -81.7871 -81.2378 -83.2520 -82.4280 -82.5195
 4     -82.5195 -81.3599 -81.4819 -81.6956 -81.2988 -83.3130 -82.4890 -82.5195
 5     -82.3669 -81.2073 -81.4819 -81.6040 -81.2683 -83.2825 -82.5806 -82.4585
 ...        ...      ...      ...      ...      ...      ...      ...      ...
 11996      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN