In [1]:
a = 3

In [2]:
b = 2

In [3]:
a + b

5

In [4]:
import pandas as pd

In [10]:
file_name = 'RS and FS neuron trace for modeling.xlsx'

In [6]:
df = pd.read_excel('RS and FS neuron trace for modeling.xlsx')

In [7]:
df

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.000000,-150.000000,-100.000000,-50.000000,0.000000,50.000000,100.000000,150.000000,200.000000,...,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.000000,-80.200195,-79.559326,-79.528809,-79.833984,-79.895020,-80.230713,-80.444336,-80.688477,-80.688477,...,-69.5801,-69.5496,-69.3359,-69.2139,-69.1223,-69.0308,-69.0002,-68.6340,-69.2749,-69.2444
2,0.100000,-80.200195,-79.650879,-79.467773,-79.650879,-80.078125,-80.291748,-80.505371,-80.688477,-80.841064,...,-69.2749,-69.4885,-69.2139,-69.1528,-69.1833,-69.2139,-69.0918,-68.6340,-69.1528,-69.2444
3,0.200000,-80.230713,-79.589844,-79.498291,-79.772949,-79.986572,-80.322266,-80.444336,-80.749512,-80.657959,...,-69.3970,-69.7021,-69.2749,-69.1528,-69.1223,-69.0613,-69.1833,-68.7561,-69.2444,-69.2749
4,0.300000,-80.230713,-79.620361,-79.498291,-79.681396,-79.986572,-80.200195,-80.444336,-80.657959,-80.871582,...,-69.3970,-69.5496,-69.2444,-69.2139,-69.2749,-69.0918,-69.1223,-68.7256,-69.0918,-69.3665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10997,1099.599976,-79.620361,-79.559326,-79.772949,-79.986572,-80.200195,-80.474854,-80.627441,-80.780029,-81.085205,...,-69.6716,-69.3665,-69.2139,-69.0918,-69.1528,-68.9392,-68.6646,-69.1528,-69.3665,-70.7092
10998,1099.699951,-79.620361,-79.376221,-79.650879,-80.047607,-80.352783,-80.444336,-80.780029,-80.810547,-80.993652,...,-69.5496,-69.2749,-69.2444,-69.2444,-69.1528,-68.9697,-68.5425,-69.0613,-69.3665,-70.7397
10999,1099.800049,-79.528809,-79.528809,-79.833984,-79.895020,-80.200195,-80.444336,-80.688477,-80.718994,-80.993652,...,-69.5801,-69.3359,-69.2139,-69.1223,-69.0613,-68.9697,-68.6340,-69.0918,-69.2749,-70.6482
11000,1099.900024,-79.650879,-79.467773,-79.650879,-80.017090,-80.322266,-80.444336,-80.718994,-80.841064,-80.963135,...,-69.3970,-69.2444,-69.2139,-69.2139,-69.1223,-69.0308,-68.5730,-69.1223,-69.3054,-70.7092
11001,NaN,-80.322266,-80.444336,-80.718994,-80.841064,-80.963135,-82.824707,-83.648682,-84.289551,-84.442139,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(df)

        Unnamed: 0  20190219 Slice 1 Cell 0  Unnamed: 2  Unnamed: 3  \
0              NaN              -200.000000 -150.000000 -100.000000
1         0.000000               -80.200195  -79.559326  -79.528809
2         0.100000               -80.200195  -79.650879  -79.467773
3         0.200000               -80.230713  -79.589844  -79.498291
4         0.300000               -80.230713  -79.620361  -79.498291
...            ...                      ...         ...         ...
10997  1099.599976               -79.620361  -79.559326  -79.772949
10998  1099.699951               -79.620361  -79.376221  -79.650879
10999  1099.800049               -79.528809  -79.528809  -79.833984
11000  1099.900024               -79.650879  -79.467773  -79.650879
11001          NaN               -80.322266  -80.444336  -80.718994

       Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0      -50.000000    0.000000   50.000000  100.000000  150.000000  200.000000
1      -79.833984  -79.895020  -80.230713  -80.444336  -80.688477  -80.688477
2      -79.650879  -80.078125  -80.291748  -80.505371  -80.688477  -80.841064
3      -79.772949  -79.986572  -80.322266  -80.444336  -80.749512  -80.657959
4      -79.681396  -79.986572  -80.200195  -80.444336  -80.657959  -80.871582
...           ...         ...         ...         ...         ...         ...
10997  -79.986572  -80.200195  -80.474854  -80.627441  -80.780029  -81.085205
10998  -80.047607  -80.352783  -80.444336  -80.780029  -80.810547  -80.993652
10999  -79.895020  -80.200195  -80.444336  -80.688477  -80.718994  -80.993652
11000  -80.017090  -80.322266  -80.444336  -80.718994  -80.841064  -80.963135
11001  -80.841064  -80.963135  -82.824707  -83.648682  -84.289551  -84.442139

       ...  Unnamed: 49  Unnamed: 50  Unnamed: 51  Unnamed: 52  Unnamed: 53  \
0      ...     -50.0000       0.0000      50.0000     100.0000     150.0000
1      ...     -69.5801     -69.5496     -69.3359     -69.2139     -69.1223
2      ...     -69.2749     -69.4885     -69.2139     -69.1528     -69.1833
3      ...     -69.3970     -69.7021     -69.2749     -69.1528     -69.1223
4      ...     -69.3970     -69.5496     -69.2444     -69.2139     -69.2749
...    ...          ...          ...          ...          ...          ...
10997  ...     -69.6716     -69.3665     -69.2139     -69.0918     -69.1528
10998  ...     -69.5496     -69.2749     -69.2444     -69.2444     -69.1528
10999  ...     -69.5801     -69.3359     -69.2139     -69.1223     -69.0613
11000  ...     -69.3970     -69.2444     -69.2139     -69.2139     -69.1223
11001  ...          NaN          NaN          NaN          NaN          NaN

       Unnamed: 54  Unnamed: 55  Unnamed: 56  Unnamed: 57  Unnamed: 58
0         200.0000     250.0000     300.0000     350.0000     400.0000
1         -69.0308     -69.0002     -68.6340     -69.2749     -69.2444
2         -69.2139     -69.0918     -68.6340     -69.1528     -69.2444
3         -69.0613     -69.1833     -68.7561     -69.2444     -69.2749
4         -69.0918     -69.1223     -68.7256     -69.0918     -69.3665
...            ...          ...          ...          ...          ...
10997     -68.9392     -68.6646     -69.1528     -69.3665     -70.7092
10998     -68.9697     -68.5425     -69.0613     -69.3665     -70.7397
10999     -68.9697     -68.6340     -69.0918     -69.2749     -70.6482
11000     -69.0308     -68.5730     -69.1223     -69.3054     -70.7092
11001          NaN          NaN          NaN          NaN          NaN

[11002 rows x 59 columns]

In [11]:
df_sheet_index = pd.read_excel(file_name, sheet_name=1)

In [12]:
print(df_sheet_index)

        Unnamed: 0  20190219 Slice 1 Cell 0  Unnamed: 2  Unnamed: 3  \
0              NaN                -200.0000   -150.0000   -100.0000
1         0.000000                 -75.2563    -74.8901    -75.4089
2         0.100000                 -75.2869    -74.8291    -75.5310
3         0.200000                 -75.2869    -74.8596    -75.4395
4         0.300000                 -75.2563    -74.8291    -75.4700
...            ...                      ...         ...         ...
10996  1099.500000                 -74.8596    -75.4395    -74.9207
10997  1099.599976                 -74.8596    -75.4395    -74.9512
10998  1099.699951                 -74.8291    -75.4700    -74.8901
10999  1099.800049                 -74.8596    -75.4089    -74.9512
11000  1099.900024                 -74.9207    -75.5005    -74.9817

       Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0        -50.0000      0.0000     50.0000    100.0000    150.0000    200.0000
1        -74.9817    -75.4395    -75.3174    -75.1953    -75.8057    -76.4465
2        -74.9512    -75.3784    -75.3784    -75.1038    -75.8362    -76.3855
3        -74.9512    -75.4395    -75.2869    -75.1953    -75.7751    -76.3855
4        -75.0122    -75.4395    -75.3479    -75.1343    -75.8057    -76.5076
...           ...         ...         ...         ...         ...         ...
10996    -75.3784    -75.3784    -75.1038    -75.7141    -76.3855    -78.3997
10997    -75.3479    -75.3479    -75.1953    -75.8362    -76.3550    -78.3386
10998    -75.3479    -75.3174    -75.1038    -75.7751    -76.3855    -78.3997
10999    -75.4089    -75.3174    -75.1648    -75.8362    -76.4160    -78.3386
11000    -75.3174    -75.3479    -75.0732    -75.7446    -76.4160    -78.3691

       ...  Unnamed: 49  Unnamed: 50  Unnamed: 51  Unnamed: 52  Unnamed: 53  \
0      ...     -50.0000       0.0000      50.0000     100.0000     150.0000
1      ...     -73.7000     -74.4019     -74.4934     -74.5850     -74.3103
2      ...     -73.7000     -74.4019     -74.4629     -74.5544     -74.3103
3      ...     -73.7000     -74.4324     -74.4934     -74.5850     -74.3408
4      ...     -73.7000     -74.4019     -74.4934     -74.5850     -74.3408
...    ...          ...          ...          ...          ...          ...
10996  ...     -74.4019     -74.4934     -74.5850     -74.3103     -75.1343
10997  ...     -74.4019     -74.4934     -74.5544     -74.3103     -75.1038
10998  ...     -74.4324     -74.4934     -74.5544     -74.3103     -75.0732
10999  ...     -74.4324     -74.4934     -74.5544     -74.3103     -75.1038
11000  ...     -74.4019     -74.4934     -74.5544     -74.3103     -75.1038

       Unnamed: 54  Unnamed: 55  Unnamed: 56  Unnamed: 57  Unnamed: 58
0         200.0000     250.0000     300.0000     350.0000     400.0000
1         -75.1038     -74.3713     -77.1484     -78.6743     -80.0476
2         -75.0732     -74.3713     -77.1179     -78.6743     -80.0476
3         -75.1038     -74.3713     -77.1179     -78.6743     -80.0476
4         -75.1038     -74.3713     -77.0874     -78.6743     -80.0476
...            ...          ...          ...          ...          ...
10996     -74.3713     -77.0874     -78.6438     -80.0171     -79.8950
10997     -74.3713     -77.1179     -78.6438     -80.0171     -79.8950
10998     -74.3713     -77.1179     -78.6743     -80.0171     -79.8950
10999     -74.3713     -77.1179     -78.6743     -80.0171     -79.9255
11000     -74.3713     -77.1179     -78.6743     -80.0476     -79.9255

[11001 rows x 59 columns]

In [16]:
pfc_fs = pd.read_excel(file_name, sheet_name='ACC FS neuron')

print(pfc_fs)

        Unnamed: 0  20190219 Slice 1 Cell 0  Unnamed: 2  Unnamed: 3  \
0              NaN                -200.0000   -150.0000   -100.0000
1         0.000000                 -75.2563    -74.8901    -75.4089
2         0.100000                 -75.2869    -74.8291    -75.5310
3         0.200000                 -75.2869    -74.8596    -75.4395
4         0.300000                 -75.2563    -74.8291    -75.4700
...            ...                      ...         ...         ...
10996  1099.500000                 -74.8596    -75.4395    -74.9207
10997  1099.599976                 -74.8596    -75.4395    -74.9512
10998  1099.699951                 -74.8291    -75.4700    -74.8901
10999  1099.800049                 -74.8596    -75.4089    -74.9512
11000  1099.900024                 -74.9207    -75.5005    -74.9817

       Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0        -50.0000      0.0000     50.0000    100.0000    150.0000    200.0000
1        -74.9817    -75.4395    -75.3174    -75.1953    -75.8057    -76.4465
2        -74.9512    -75.3784    -75.3784    -75.1038    -75.8362    -76.3855
3        -74.9512    -75.4395    -75.2869    -75.1953    -75.7751    -76.3855
4        -75.0122    -75.4395    -75.3479    -75.1343    -75.8057    -76.5076
...           ...         ...         ...         ...         ...         ...
10996    -75.3784    -75.3784    -75.1038    -75.7141    -76.3855    -78.3997
10997    -75.3479    -75.3479    -75.1953    -75.8362    -76.3550    -78.3386
10998    -75.3479    -75.3174    -75.1038    -75.7751    -76.3855    -78.3997
10999    -75.4089    -75.3174    -75.1648    -75.8362    -76.4160    -78.3386
11000    -75.3174    -75.3479    -75.0732    -75.7446    -76.4160    -78.3691

       ...  Unnamed: 49  Unnamed: 50  Unnamed: 51  Unnamed: 52  Unnamed: 53  \
0      ...     -50.0000       0.0000      50.0000     100.0000     150.0000
1      ...     -73.7000     -74.4019     -74.4934     -74.5850     -74.3103
2      ...     -73.7000     -74.4019     -74.4629     -74.5544     -74.3103
3      ...     -73.7000     -74.4324     -74.4934     -74.5850     -74.3408
4      ...     -73.7000     -74.4019     -74.4934     -74.5850     -74.3408
...    ...          ...          ...          ...          ...          ...
10996  ...     -74.4019     -74.4934     -74.5850     -74.3103     -75.1343
10997  ...     -74.4019     -74.4934     -74.5544     -74.3103     -75.1038
10998  ...     -74.4324     -74.4934     -74.5544     -74.3103     -75.0732
10999  ...     -74.4324     -74.4934     -74.5544     -74.3103     -75.1038
11000  ...     -74.4019     -74.4934     -74.5544     -74.3103     -75.1038

       Unnamed: 54  Unnamed: 55  Unnamed: 56  Unnamed: 57  Unnamed: 58
0         200.0000     250.0000     300.0000     350.0000     400.0000
1         -75.1038     -74.3713     -77.1484     -78.6743     -80.0476
2         -75.0732     -74.3713     -77.1179     -78.6743     -80.0476
3         -75.1038     -74.3713     -77.1179     -78.6743     -80.0476
4         -75.1038     -74.3713     -77.0874     -78.6743     -80.0476
...            ...          ...          ...          ...          ...
10996     -74.3713     -77.0874     -78.6438     -80.0171     -79.8950
10997     -74.3713     -77.1179     -78.6438     -80.0171     -79.8950
10998     -74.3713     -77.1179     -78.6743     -80.0171     -79.8950
10999     -74.3713     -77.1179     -78.6743     -80.0171     -79.9255
11000     -74.3713     -77.1179     -78.6743     -80.0476     -79.9255

[11001 rows x 59 columns]

In [17]:
pfc_fs

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,...,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255

In [21]:
pfc_fs[0:13]

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,...,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.0,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.1,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.2,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.3,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
5,0.4,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,...,-73.7000,-74.4019,-74.4629,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.7048,-80.0476
6,0.5,-75.2258,-74.8901,-75.4700,-75.0427,-75.4395,-75.3174,-75.1343,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0569,-78.6743,-80.0171
7,0.6,-75.3174,-74.7986,-75.5310,-74.9512,-75.4700,-75.3174,-75.2563,-75.7446,-76.4160,...,-73.7000,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.0569,-78.6743,-80.0171
8,0.7,-75.3174,-74.9207,-75.4700,-75.0427,-75.4700,-75.2869,-75.1648,-75.7751,-76.3855,...,-73.6694,-74.3713,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.0264,-78.7048,-80.0171
9,0.8,-75.3174,-74.8291,-75.5920,-74.9207,-75.4395,-75.3479,-75.1953,-75.7141,-76.4465,...,-73.6694,-74.3713,-74.4934,-74.5544,-74.3408,-75.1038,-74.3713,-77.0264,-78.7048,-80.0476
10,0.9,-75.2869,-74.9817,-75.4395,-74.9817,-75.5005,-75.3174,-75.1648,-75.7446,-76.4465,...,-73.6694,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-76.9958,-78.6743,-80.0476
11,1.0,-75.2563,-74.8596,-75.5615,-74.9512,-75.3479,-75.3784,-75.1648,-75.7141,-76.4160,...,-73.6389,-74.4019,-74.4934,-74.5850,-74.3408,-75.1343,-74.3713,-76.9958,-78.7048,-80.0171
12,1.1,-75.2869,-74.9207,-75.4700,-74.9512,-75.4089,-75.3174,-75.1648,-75.7751,-76.4465,...,-73.6389,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-76.9958,-78.7048,-80.0476

In [26]:
pfc_fs.iloc[:, 1:14]

,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,-78.3386,-79.9561,-80.8716,-82.0312
2,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,-78.3691,-80.0171,-80.8105,-81.9702
3,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,-78.3081,-79.9255,-80.9021,-82.0618
4,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,-78.3691,-79.9561,-80.7800,-81.9702
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,-79.9866,-80.7800,-82.0007,-82.4585
10997,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,-79.9866,-80.8105,-81.9702,-82.3975
10998,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,-80.0171,-80.7495,-81.9702,-82.4585
10999,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,-79.9255,-80.8411,-82.0007,-82.3669
11000,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,-79.9561,-80.6885,-81.9702,-82.3975