In [26]:
import pickle
import pandas as pd
import numpy as np

with open('slice_data.pickle', 'rb') as handle:
    raw_data = pickle.load(handle)

In [2]:
raw_data.keys()

dict_keys(['ACC_FS', 'PPC_FS', 'ACC_RS', 'PPC_RS'])

In [3]:
data = raw_data['ACC_FS']

Get the index of NaN and find the spots to separate the columns

In [21]:
n_column = data.iloc[0,:].size

In [22]:
data.iloc[0,1:14]

20190219 Slice 1 Cell 0   -200.0
Unnamed: 2                -150.0
Unnamed: 3                -100.0
Unnamed: 4                 -50.0
Unnamed: 5                   0.0
Unnamed: 6                  50.0
Unnamed: 7                 100.0
Unnamed: 8                 150.0
Unnamed: 9                 200.0
Unnamed: 10                250.0
Unnamed: 11                300.0
Unnamed: 12                350.0
Unnamed: 13                400.0
Name: 0, dtype: float64

In [25]:
data.iloc[0,58]

400.0

In [38]:
starting_index = np.arange (1,n_column+1, 15)

In [39]:
starting_index

array([ 1, 16, 31, 46])

In [40]:
cell_list = []

In [41]:
for i in starting_index:
    cell_data = data.iloc[:,i:i+13]
    cell_list.append(cell_data)

In [45]:
len(cell_list)

4

In [54]:
cell_list[0]

,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,-78.3386,-79.9561,-80.8716,-82.0312
2,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,-78.3691,-80.0171,-80.8105,-81.9702
3,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,-78.3081,-79.9255,-80.9021,-82.0618
4,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,-78.3691,-79.9561,-80.7800,-81.9702
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,-79.9866,-80.7800,-82.0007,-82.4585
10997,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,-79.9866,-80.8105,-81.9702,-82.3975
10998,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,-80.0171,-80.7495,-81.9702,-82.4585
10999,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,-79.9255,-80.8411,-82.0007,-82.3669
11000,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,-79.9561,-80.6885,-81.9702,-82.3975

In [36]:
a

array([ 1, 16, 31, 46])

In [ ]:
range(3, 20, 2)

In [ ]:

i = 1

[i:i+13]

j = i + 13 + 2

[i:i+13]

[just_before+2:i:13]

In [5]:
data_no_time = data.iloc[1:,:]

In [7]:
clamp_levels = data.iloc[0, :]

In [9]:
clamp_levels[1:]

20190219 Slice 1 Cell 0   -200.0
Unnamed: 2                -150.0
Unnamed: 3                -100.0
Unnamed: 4                 -50.0
Unnamed: 5                   0.0
Unnamed: 6                  50.0
Unnamed: 7                 100.0
Unnamed: 8                 150.0
Unnamed: 9                 200.0
Unnamed: 10                250.0
Unnamed: 11                300.0
Unnamed: 12                350.0
Unnamed: 13                400.0
Unnamed: 14                  NaN
Unnamed: 15                  NaN
20180620 Slice 1 Cell 0   -200.0
Unnamed: 17               -150.0
Unnamed: 18               -100.0
Unnamed: 19                -50.0
Unnamed: 20                  0.0
Unnamed: 21                 50.0
Unnamed: 22                100.0
Unnamed: 23                150.0
Unnamed: 24                200.0
Unnamed: 25                250.0
Unnamed: 26                300.0
Unnamed: 27                350.0
Unnamed: 28                400.0
Unnamed: 29                  NaN
Unnamed: 30                  NaN
20180620 Slice 1 Cell 1   -200.0
Unnamed: 32               -150.0
Unnamed: 33               -100.0
Unnamed: 34                -50.0
Unnamed: 35                  0.0
Unnamed: 36                 50.0
Unnamed: 37                100.0
Unnamed: 38                150.0
Unnamed: 39                200.0
Unnamed: 40                250.0
Unnamed: 41                300.0
Unnamed: 42                350.0
Unnamed: 43                400.0
Unnamed: 44                  NaN
Unnamed: 45                  NaN
20180720 Slice 2_Cell 2   -200.0
Unnamed: 47               -150.0
Unnamed: 48               -100.0
Unnamed: 49                -50.0
Unnamed: 50                  0.0
Unnamed: 51                 50.0
Unnamed: 52                100.0
Unnamed: 53                150.0
Unnamed: 54                200.0
Unnamed: 55                250.0
Unnamed: 56                300.0
Unnamed: 57                350.0
Unnamed: 58                400.0
Name: 0, dtype: float64

In [10]:
clamp_levels_string = pd.Series(clamp_levels[1:], dtype="string")

In [6]:
data_no_time

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
5,0.400000,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,...,-73.7000,-74.4019,-74.4629,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.7048,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255

In [13]:
data_no_time.columns = clamp_levels_string

ValueError: Length mismatch: Expected axis has 59 elements, new values have 58 elements

In [15]:
clamp_levels_string.size

58

In [17]:
data_no_time.iloc[0,:].size

59

In [18]:
data_no_time.iloc[0,:]

Unnamed: 0                  0.0000
20190219 Slice 1 Cell 0   -75.2563
Unnamed: 2                -74.8901
Unnamed: 3                -75.4089
Unnamed: 4                -74.9817
Unnamed: 5                -75.4395
Unnamed: 6                -75.3174
Unnamed: 7                -75.1953
Unnamed: 8                -75.8057
Unnamed: 9                -76.4465
Unnamed: 10               -78.3386
Unnamed: 11               -79.9561
Unnamed: 12               -80.8716
Unnamed: 13               -82.0312
Unnamed: 14                    NaN
Unnamed: 15                 0.0000
20180620 Slice 1 Cell 0   -75.9583
Unnamed: 17               -75.9583
Unnamed: 18               -75.9888
Unnamed: 19               -75.9888
Unnamed: 20               -76.1414
Unnamed: 21               -75.9888
Unnamed: 22               -75.8667
Unnamed: 23               -76.3550
Unnamed: 24               -76.6602
Unnamed: 25               -77.7283
Unnamed: 26               -78.8574
Unnamed: 27               -79.6509
Unnamed: 28               -80.4749
Unnamed: 29                    NaN
Unnamed: 30                 0.0000
20180620 Slice 1 Cell 1   -70.9229
Unnamed: 32               -71.1670
Unnamed: 33               -70.1294
Unnamed: 34               -70.5872
Unnamed: 35               -71.5332
Unnamed: 36               -70.8313
Unnamed: 37               -72.1741
Unnamed: 38               -71.8079
Unnamed: 39               -73.3643
Unnamed: 40               -74.6765
Unnamed: 41               -76.3855
Unnamed: 42               -76.9043
Unnamed: 43               -75.5005
Unnamed: 44                    NaN
Unnamed: 45                 0.0000
20180720 Slice 2_Cell 2   -73.3337
Unnamed: 47               -73.7305
Unnamed: 48               -73.7610
Unnamed: 49               -73.7000
Unnamed: 50               -74.4019
Unnamed: 51               -74.4934
Unnamed: 52               -74.5850
Unnamed: 53               -74.3103
Unnamed: 54               -75.1038
Unnamed: 55               -74.3713
Unnamed: 56               -77.1484
Unnamed: 57               -78.6743
Unnamed: 58               -80.0476
Name: 1, dtype: float64

In [11]:
clamp_levels_string

20190219 Slice 1 Cell 0    -200.0
Unnamed: 2                 -150.0
Unnamed: 3                 -100.0
Unnamed: 4                  -50.0
Unnamed: 5                    0.0
Unnamed: 6                   50.0
Unnamed: 7                  100.0
Unnamed: 8                  150.0
Unnamed: 9                  200.0
Unnamed: 10                 250.0
Unnamed: 11                 300.0
Unnamed: 12                 350.0
Unnamed: 13                 400.0
Unnamed: 14                  <NA>
Unnamed: 15                  <NA>
20180620 Slice 1 Cell 0    -200.0
Unnamed: 17                -150.0
Unnamed: 18                -100.0
Unnamed: 19                 -50.0
Unnamed: 20                   0.0
Unnamed: 21                  50.0
Unnamed: 22                 100.0
Unnamed: 23                 150.0
Unnamed: 24                 200.0
Unnamed: 25                 250.0
Unnamed: 26                 300.0
Unnamed: 27                 350.0
Unnamed: 28                 400.0
Unnamed: 29                  <NA>
Unnamed: 30                  <NA>
20180620 Slice 1 Cell 1    -200.0
Unnamed: 32                -150.0
Unnamed: 33                -100.0
Unnamed: 34                 -50.0
Unnamed: 35                   0.0
Unnamed: 36                  50.0
Unnamed: 37                 100.0
Unnamed: 38                 150.0
Unnamed: 39                 200.0
Unnamed: 40                 250.0
Unnamed: 41                 300.0
Unnamed: 42                 350.0
Unnamed: 43                 400.0
Unnamed: 44                  <NA>
Unnamed: 45                  <NA>
20180720 Slice 2_Cell 2    -200.0
Unnamed: 47                -150.0
Unnamed: 48                -100.0
Unnamed: 49                 -50.0
Unnamed: 50                   0.0
Unnamed: 51                  50.0
Unnamed: 52                 100.0
Unnamed: 53                 150.0
Unnamed: 54                 200.0
Unnamed: 55                 250.0
Unnamed: 56                 300.0
Unnamed: 57                 350.0
Unnamed: 58                 400.0
Name: 0, dtype: string

In [39]:
data

,NaN,-200.0,-150.0,-100.0,-50.0,0.0,50.0,100.0,150.0,200.0,...,-50.0,0.0,50.0,100.0,150.0,200.0,250.0,300.0,350.0,400.0
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
5,0.400000,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,...,-73.7000,-74.4019,-74.4629,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.7048,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255

In [15]:
data.iloc[:,1]

0       -200.0000
1        -75.2563
2        -75.2869
3        -75.2869
4        -75.2563
           ...
10996    -74.8596
10997    -74.8596
10998    -74.8291
10999    -74.8596
11000    -74.9207
Name: 20190219 Slice 1 Cell 0, Length: 11001, dtype: float64

In [16]:
clamp_levels = data.iloc[0, :]

In [41]:
data.iloc[0,:]

0
NaN        0.0000
-200.0   -75.2563
-150.0   -74.8901
-100.0   -75.4089
-50.0    -74.9817
0.0      -75.4395
50.0     -75.3174
100.0    -75.1953
150.0    -75.8057
200.0    -76.4465
250.0    -78.3386
300.0    -79.9561
350.0    -80.8716
400.0    -82.0312
NaN           NaN
NaN        0.0000
-200.0   -75.9583
-150.0   -75.9583
-100.0   -75.9888
-50.0    -75.9888
0.0      -76.1414
50.0     -75.9888
100.0    -75.8667
150.0    -76.3550
200.0    -76.6602
250.0    -77.7283
300.0    -78.8574
350.0    -79.6509
400.0    -80.4749
NaN           NaN
NaN        0.0000
-200.0   -70.9229
-150.0   -71.1670
-100.0   -70.1294
-50.0    -70.5872
0.0      -71.5332
50.0     -70.8313
100.0    -72.1741
150.0    -71.8079
200.0    -73.3643
250.0    -74.6765
300.0    -76.3855
350.0    -76.9043
400.0    -75.5005
NaN           NaN
NaN        0.0000
-200.0   -73.3337
-150.0   -73.7305
-100.0   -73.7610
-50.0    -73.7000
0.0      -74.4019
50.0     -74.4934
100.0    -74.5850
150.0    -74.3103
200.0    -75.1038
250.0    -74.3713
300.0    -77.1484
350.0    -78.6743
400.0    -80.0476
Name: 1, dtype: float64

In [17]:
clamp_levels_string = pd.Series(clamp_levels, dtype="string")

In [18]:
data.columns = clamp_levels_string

In [38]:
data.iloc[:,0]

TypeError: boolean value of NA is ambiguous

In [21]:
data['100.0']

c:\Users\KBRI\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3361: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return self._engine.get_loc(casted_key)

TypeError: Cannot convert bool to numpy.ndarray

In [22]:
data['-200.0']

TypeError: Cannot convert bool to numpy.ndarray

In [23]:
test = data

In [24]:
test.drop([0], axis=0, inplace=True)

In [25]:
rmp_time  = data.iloc[:, 0]

In [26]:
rmp_time[1:]

TypeError: boolean value of NA is ambiguous

In [27]:
test

,NaN,-200.0,-150.0,-100.0,-50.0,0.0,50.0,100.0,150.0,200.0,...,-50.0,0.0,50.0,100.0,150.0,200.0,250.0,300.0,350.0,400.0
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
5,0.400000,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,...,-73.7000,-74.4019,-74.4629,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.7048,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255

In [36]:
test.iloc[:, 1]

1       -75.2563
2       -75.2869
3       -75.2869
4       -75.2563
5       -75.2869
          ...
10996   -74.8596
10997   -74.8596
10998   -74.8291
10999   -74.8596
11000   -74.9207
Name: -200.0, Length: 11000, dtype: float64

In [29]:
rmp_time  = test.iloc[1:, 0]

In [30]:
rmp_time

TypeError: boolean value of NA is ambiguous

In [43]:
test.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [24]:
clamp_levels

Unnamed: 0                   NaN
20190219 Slice 1 Cell 0   -200.0
Unnamed: 2                -150.0
Unnamed: 3                -100.0
Unnamed: 4                 -50.0
Unnamed: 5                   0.0
Unnamed: 6                  50.0
Unnamed: 7                 100.0
Unnamed: 8                 150.0
Unnamed: 9                 200.0
Unnamed: 10                250.0
Unnamed: 11                300.0
Unnamed: 12                350.0
Unnamed: 13                400.0
Unnamed: 14                  NaN
Unnamed: 15                  NaN
20180620 Slice 1 Cell 0   -200.0
Unnamed: 17               -150.0
Unnamed: 18               -100.0
Unnamed: 19                -50.0
Unnamed: 20                  0.0
Unnamed: 21                 50.0
Unnamed: 22                100.0
Unnamed: 23                150.0
Unnamed: 24                200.0
Unnamed: 25                250.0
Unnamed: 26                300.0
Unnamed: 27                350.0
Unnamed: 28                400.0
Unnamed: 29                  NaN
Unnamed: 30                  NaN
20180620 Slice 1 Cell 1   -200.0
Unnamed: 32               -150.0
Unnamed: 33               -100.0
Unnamed: 34                -50.0
Unnamed: 35                  0.0
Unnamed: 36                 50.0
Unnamed: 37                100.0
Unnamed: 38                150.0
Unnamed: 39                200.0
Unnamed: 40                250.0
Unnamed: 41                300.0
Unnamed: 42                350.0
Unnamed: 43                400.0
Unnamed: 44                  NaN
Unnamed: 45                  NaN
20180720 Slice 2_Cell 2   -200.0
Unnamed: 47               -150.0
Unnamed: 48               -100.0
Unnamed: 49                -50.0
Unnamed: 50                  0.0
Unnamed: 51                 50.0
Unnamed: 52                100.0
Unnamed: 53                150.0
Unnamed: 54                200.0
Unnamed: 55                250.0
Unnamed: 56                300.0
Unnamed: 57                350.0
Unnamed: 58                400.0
Name: 0, dtype: float64

In [7]:
data.head()

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,...,-50.0,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.0,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.1,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.2,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.3,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476

In [8]:
data

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,...,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255

In [9]:
rmp_time  = data.iloc[:, 0]

In [10]:
rmp_time

0                NaN
1           0.000000
2           0.100000
3           0.200000
4           0.300000
            ...
10996    1099.500000
10997    1099.599976
10998    1099.699951
10999    1099.800049
11000    1099.900024
Name: Unnamed: 0, Length: 11001, dtype: float64

In [11]:
a

In [12]:
clamp_levels

20190219 Slice 1 Cell 0   -200.0
Unnamed: 2                -150.0
Unnamed: 3                -100.0
Unnamed: 4                 -50.0
Unnamed: 5                   0.0
Unnamed: 6                  50.0
Unnamed: 7                 100.0
Unnamed: 8                 150.0
Unnamed: 9                 200.0
Unnamed: 10                250.0
Unnamed: 11                300.0
Unnamed: 12                350.0
Unnamed: 13                400.0
Name: 0, dtype: float64

In [13]:
import pandas as pd

In [14]:
clamp_levels_string = pd.Series(clamp_levels, dtype="string")

In [15]:
clamp_levels_string

20190219 Slice 1 Cell 0    -200.0
Unnamed: 2                 -150.0
Unnamed: 3                 -100.0
Unnamed: 4                  -50.0
Unnamed: 5                    0.0
Unnamed: 6                   50.0
Unnamed: 7                  100.0
Unnamed: 8                  150.0
Unnamed: 9                  200.0
Unnamed: 10                 250.0
Unnamed: 11                 300.0
Unnamed: 12                 350.0
Unnamed: 13                 400.0
Name: 0, dtype: string

In [16]:
first_cell = data.iloc[1:, 1:14]

In [17]:
first_cell

,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
1,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,-78.3386,-79.9561,-80.8716,-82.0312
2,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,-78.3691,-80.0171,-80.8105,-81.9702
3,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,-78.3081,-79.9255,-80.9021,-82.0618
4,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,-78.3691,-79.9561,-80.7800,-81.9702
5,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,-78.3691,-79.9255,-80.8716,-82.0618
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,-79.9866,-80.7800,-82.0007,-82.4585
10997,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,-79.9866,-80.8105,-81.9702,-82.3975
10998,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,-80.0171,-80.7495,-81.9702,-82.4585
10999,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,-79.9255,-80.8411,-82.0007,-82.3669
11000,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,-79.9561,-80.6885,-81.9702,-82.3975

In [18]:
first_cell.columns = clamp_levels_string

In [19]:
first_cell

,-200.0,-150.0,-100.0,-50.0,0.0,50.0,100.0,150.0,200.0,250.0,300.0,350.0,400.0
1,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,-78.3386,-79.9561,-80.8716,-82.0312
2,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,-78.3691,-80.0171,-80.8105,-81.9702
3,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,-78.3081,-79.9255,-80.9021,-82.0618
4,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,-78.3691,-79.9561,-80.7800,-81.9702
5,-75.2869,-74.8596,-75.4395,-74.9207,-75.4395,-75.3174,-75.2258,-75.7446,-76.4771,-78.3691,-79.9255,-80.8716,-82.0618
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,-79.9866,-80.7800,-82.0007,-82.4585
10997,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,-79.9866,-80.8105,-81.9702,-82.3975
10998,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,-80.0171,-80.7495,-81.9702,-82.4585
10999,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,-79.9255,-80.8411,-82.0007,-82.3669
11000,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,-79.9561,-80.6885,-81.9702,-82.3975

In [20]:
data

,Unnamed: 0,20190219 Slice 1 Cell 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,-200.0000,-150.0000,-100.0000,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,...,-50.0000,0.0000,50.0000,100.0000,150.0000,200.0000,250.0000,300.0000,350.0000,400.0000
1,0.000000,-75.2563,-74.8901,-75.4089,-74.9817,-75.4395,-75.3174,-75.1953,-75.8057,-76.4465,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3103,-75.1038,-74.3713,-77.1484,-78.6743,-80.0476
2,0.100000,-75.2869,-74.8291,-75.5310,-74.9512,-75.3784,-75.3784,-75.1038,-75.8362,-76.3855,...,-73.7000,-74.4019,-74.4629,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0476
3,0.200000,-75.2869,-74.8596,-75.4395,-74.9512,-75.4395,-75.2869,-75.1953,-75.7751,-76.3855,...,-73.7000,-74.4324,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476
4,0.300000,-75.2563,-74.8291,-75.4700,-75.0122,-75.4395,-75.3479,-75.1343,-75.8057,-76.5076,...,-73.7000,-74.4019,-74.4934,-74.5850,-74.3408,-75.1038,-74.3713,-77.0874,-78.6743,-80.0476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,1099.500000,-74.8596,-75.4395,-74.9207,-75.3784,-75.3784,-75.1038,-75.7141,-76.3855,-78.3997,...,-74.4019,-74.4934,-74.5850,-74.3103,-75.1343,-74.3713,-77.0874,-78.6438,-80.0171,-79.8950
10997,1099.599976,-74.8596,-75.4395,-74.9512,-75.3479,-75.3479,-75.1953,-75.8362,-76.3550,-78.3386,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6438,-80.0171,-79.8950
10998,1099.699951,-74.8291,-75.4700,-74.8901,-75.3479,-75.3174,-75.1038,-75.7751,-76.3855,-78.3997,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.0732,-74.3713,-77.1179,-78.6743,-80.0171,-79.8950
10999,1099.800049,-74.8596,-75.4089,-74.9512,-75.4089,-75.3174,-75.1648,-75.8362,-76.4160,-78.3386,...,-74.4324,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0171,-79.9255
11000,1099.900024,-74.9207,-75.5005,-74.9817,-75.3174,-75.3479,-75.0732,-75.7446,-76.4160,-78.3691,...,-74.4019,-74.4934,-74.5544,-74.3103,-75.1038,-74.3713,-77.1179,-78.6743,-80.0476,-79.9255